// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OverLab.Api;

#nullable disable

namespace OverLab.Api.Migrations
{
    [DbContext(typeof(OverLabDbContext))]
    [Migration("20241020143709_TweakModel3")]
    partial class TweakModel3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExerciseExercisePlan", b =>
                {
                    b.Property<string>("ExercisePlansId")
                        .HasColumnType("text")
                        .HasColumnName("exercise_plans_id");

                    b.Property<string>("PossibleExercisesId")
                        .HasColumnType("text")
                        .HasColumnName("possible_exercises_id");

                    b.HasKey("ExercisePlansId", "PossibleExercisesId")
                        .HasName("pk_exercise_exercise_plan");

                    b.HasIndex("PossibleExercisesId")
                        .HasDatabaseName("ix_exercise_exercise_plan_possible_exercises_id");

                    b.ToTable("exercise_exercise_plan", (string)null);
                });

            modelBuilder.Entity("OverLab.Api.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_exercise");

                    b.ToTable("exercise", (string)null);
                });

            modelBuilder.Entity("OverLab.Api.ExercisePlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_exercise_plans");

                    b.ToTable("exercise_plans", (string)null);
                });

            modelBuilder.Entity("OverLab.Api.Workout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_canceled");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_workout");

                    b.HasIndex("IsCanceled")
                        .HasDatabaseName("ix_workout_is_canceled");

                    b.ToTable("workout", (string)null);
                });

            modelBuilder.Entity("OverLab.Api.WorkoutExercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ExerciseId")
                        .HasColumnType("text")
                        .HasColumnName("exercise_id");

                    b.Property<string>("ExercisePlanId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercise_plan_id");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finished");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("WorkoutId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workout_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_exercise");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_workout_exercise_exercise_id");

                    b.HasIndex("ExercisePlanId")
                        .HasDatabaseName("ix_workout_exercise_exercise_plan_id");

                    b.HasIndex("IsFinished")
                        .HasDatabaseName("ix_workout_exercise_is_finished");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("ix_workout_exercise_workout_id");

                    b.ToTable("workout_exercise", (string)null);
                });

            modelBuilder.Entity("OverLab.Api.WorkoutExerciseSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("Reps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reps");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.Property<string>("WorkoutExerciseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workout_exercise_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_exercise_set");

                    b.HasIndex("RecordedAtUtc")
                        .HasDatabaseName("ix_workout_exercise_set_recorded_at_utc");

                    b.HasIndex("WorkoutExerciseId")
                        .HasDatabaseName("ix_workout_exercise_set_workout_exercise_id");

                    b.ToTable("workout_exercise_set", (string)null);
                });

            modelBuilder.Entity("ExerciseExercisePlan", b =>
                {
                    b.HasOne("OverLab.Api.ExercisePlan", null)
                        .WithMany()
                        .HasForeignKey("ExercisePlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_exercise_plan_exercise_plans_exercise_plans_id");

                    b.HasOne("OverLab.Api.Exercise", null)
                        .WithMany()
                        .HasForeignKey("PossibleExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_exercise_plan_exercise_possible_exercises_id");
                });

            modelBuilder.Entity("OverLab.Api.WorkoutExercise", b =>
                {
                    b.HasOne("OverLab.Api.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .HasConstraintName("fk_workout_exercise_exercise_exercise_id");

                    b.HasOne("OverLab.Api.ExercisePlan", "ExercisePlan")
                        .WithMany()
                        .HasForeignKey("ExercisePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_exercise_exercise_plans_exercise_plan_id");

                    b.HasOne("OverLab.Api.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_exercise_workout_workout_id");

                    b.Navigation("Exercise");

                    b.Navigation("ExercisePlan");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("OverLab.Api.WorkoutExerciseSet", b =>
                {
                    b.HasOne("OverLab.Api.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_exercise_set_workout_exercise_workout_exercise_id");

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("OverLab.Api.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("OverLab.Api.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
