name: Deploy

on:
  push:
    branches:
      - "main"
      - "develop"
      - "hotfix"

env:
  REGISTRY: ghcr.io
  WEB_UI_IMAGE: overlab-web
  API_IMAGE: overlab-api

jobs:
  build-web-ui:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/ewancoder/${{ env.WEB_UI_IMAGE }}

      - name: Build and push Production Web UI Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./frontend
          file: frontend/Dockerfile-production
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Development Web UI Docker image
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./frontend
          file: frontend/Dockerfile-development
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build-web-ui]

    permissions:
      contents: read

    steps:
      - name: Deploy to DO
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          #passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            curl https://raw.githubusercontent.com/ewancoder/overlab/main/docker-compose-production.yml > /tmp/overlab-docker-compose.yml
            docker compose -f /tmp/overlab-docker-compose.yml pull
            docker compose -f /tmp/overlab-docker-compose.yml up -d
